#!/usr/bin/env bash
# Generates a reproducible test git repository in .repositories/test-repo/.
#
# Covers all git states in the MVP scope (specs/git.md §1):
#   - history of several commits (main branch)
#   - modified unstaged file
#   - untracked file
#   - added (staged) file
#   - partially staged file (one hunk in the index, another not)
#   - deleted unstaged file
#
# Usage: scripts/seed-test-repo.sh
#
# Reproducible: fixed identity and dates → stable commit OIDs.
# Re-runnable: recreates the repository from scratch. The .repositories/ folder is gitignored.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
target="$repo_root/.repositories/test-repo"

rm -rf "$target"
mkdir -p "$target"

git -c init.defaultBranch=main init -q "$target"

run() { git -C "$target" "$@"; }

run config user.name "Helm Test"
run config user.email "test@helm.local"
run config commit.gpgsign false

export GIT_AUTHOR_NAME="Helm Test"
export GIT_AUTHOR_EMAIL="test@helm.local"
export GIT_COMMITTER_NAME="Helm Test"
export GIT_COMMITTER_EMAIL="test@helm.local"

commit() { # $1 = message, $2 = ISO date (author + committer fixed)
  GIT_AUTHOR_DATE="$2" GIT_COMMITTER_DATE="$2" run commit -q -m "$1"
}

# --- Commit 1: foundation -----------------------------------------------------
cat > "$target/README.md" <<'EOF'
# test-repo

Test repository for helm. Regenerated by `scripts/seed-test-repo.sh`.
EOF

mkdir -p "$target/lib"
cat > "$target/lib/util.py" <<'EOF'
def add(a, b):
    return a + b


def sub(a, b):
    return a - b


def mul(a, b):
    return a * b
EOF

cat > "$target/app.py" <<'EOF'
from lib.util import add


def main():
    print(add(1, 2))


if __name__ == "__main__":
    main()
EOF

run add README.md app.py lib/util.py
commit "init: project foundation" "2026-01-05T09:00:00"

# --- Commit 2: docs + app evolution ------------------------------------------
mkdir -p "$target/docs"
cat > "$target/docs/guide.md" <<'EOF'
# Guide

Example documentation.
EOF

cat > "$target/app.py" <<'EOF'
from lib.util import add, sub


def main():
    print(add(1, 2))
    print(sub(5, 3))


if __name__ == "__main__":
    main()
EOF

run add app.py docs/guide.md
commit "docs: add the guide and extend app" "2026-02-10T14:30:00"

# --- Commit 3: additional module ---------------------------------------------
cat > "$target/lib/extra.py" <<'EOF'
def square(n):
    return n * n
EOF

run add lib/extra.py
commit "feat: extra module" "2026-03-15T11:15:00"

# --- Uncommitted states -------------------------------------------------------

# 1) Modified unstaged file.
cat >> "$target/app.py" <<'EOF'

# uncommitted draft
EOF

# 2) Untracked file.
cat > "$target/scratch.txt" <<'EOF'
work-in-progress notes, not tracked yet
EOF

# 3) Added (staged) file.
cat > "$target/feature.py" <<'EOF'
def feature():
    return "wip"
EOF
run add feature.py

# 4) Partially staged file: one change in the index, another not.
#    Top change (add) -> staged; bottom change (mul) -> left in the worktree.
cat > "$target/lib/util.py" <<'EOF'
def add(a, b):
    """Sum of two numbers."""
    return a + b


def sub(a, b):
    return a - b


def mul(a, b):
    return a * b
EOF
run add lib/util.py

cat > "$target/lib/util.py" <<'EOF'
def add(a, b):
    """Sum of two numbers."""
    return a + b


def sub(a, b):
    return a - b


def mul(a, b):
    """Product of two numbers."""
    return a * b
EOF

# 5) Deleted unstaged file.
rm "$target/docs/guide.md"

echo "Test repository generated: $target"
echo
echo "History:"
run --no-pager log --oneline
echo
echo "Status:"
run -c color.status=always status --short
